apiVersion: v1
kind: Namespace
metadata:
  name: react-vuln-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-vuln-app
  namespace: react-vuln-app
  labels:
    app: react-vuln-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-vuln-app
  template:
    metadata:
      labels:
        app: react-vuln-app
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: react-vuln-app
        image: ghcr.io/$GHCR_USER/react-vuln-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-vuln-app-service
  namespace: react-vuln-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: react-vuln-app